#!/usr/bin/env node
/**
 * generate-palette.js
 *
 * Reads every @radix-ui/colors CSS file and re-maps the selectors to
 * the Davinci [data-theme] convention (dark-as-default):
 *
 *   Radix light  :root, .light, .light-theme  →  [data-theme="light"]
 *   Radix dark   .dark, .dark-theme           →  :root, [data-theme="dark"]
 *   Radix root   :root (white/black alpha)    →  :root  (unchanged)
 *
 * Outputs:  ../palette.css
 *
 * Usage (from project root):
 *   node scripts/generate-palette.js
 *
 * Or via storybook package script:
 *   cd storybook && npm run generate-palette
 *
 * To upgrade: npm update @radix-ui/colors in /storybook, then re-run.
 */

const fs   = require('fs');
const path = require('path');

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const RADIX_DIR = path.join(__dirname, '../storybook/node_modules/@radix-ui/colors');
const OUT_FILE  = path.join(__dirname, '../palette.css');

if (!fs.existsSync(RADIX_DIR)) {
  console.error(`✗ @radix-ui/colors not found at ${RADIX_DIR}`);
  console.error('  Run: cd storybook && npm install --save-dev @radix-ui/colors');
  process.exit(1);
}

const pkg = JSON.parse(fs.readFileSync(path.join(RADIX_DIR, 'package.json'), 'utf8'));

// ---------------------------------------------------------------------------
// All 31 Radix color scales in semantic order
// ---------------------------------------------------------------------------

const SCALES = [
  // Achromatic neutrals
  'gray', 'mauve', 'slate', 'sage', 'olive', 'sand',
  // Chromatic
  'tomato', 'red', 'ruby', 'crimson', 'pink', 'plum',
  'purple', 'violet', 'iris', 'indigo', 'blue',
  'cyan', 'teal', 'jade', 'green', 'grass', 'lime',
  'yellow', 'amber', 'orange',
  'brown', 'bronze', 'gold',
  'sky', 'mint',
];

// ---------------------------------------------------------------------------
// Selector transformation
// ---------------------------------------------------------------------------

function transformSelectors(css) {
  return css
    // Light: :root, .light, .light-theme  →  [data-theme="light"]
    .replace(/:root, \.light, \.light-theme/g, '[data-theme="light"]')
    // Dark:  .dark, .dark-theme           →  :root, [data-theme="dark"]
    .replace(/\.dark, \.dark-theme/g, ':root, [data-theme="dark"]');
  // :root alone (white/black alpha) is unchanged
}

function readScale(filename) {
  const filepath = path.join(RADIX_DIR, filename);
  return fs.existsSync(filepath) ? fs.readFileSync(filepath, 'utf8') : '';
}

// ---------------------------------------------------------------------------
// Build output
// ---------------------------------------------------------------------------

const lines = [];

lines.push(`/* ${'='.repeat(60)}`);
lines.push(`   Davinci Design System — Radix Color Palette`);
lines.push(`   Auto-generated by scripts/generate-palette.js`);
lines.push(`   Source: @radix-ui/colors v${pkg.version}`);
lines.push(`   DO NOT EDIT — regenerate with: cd storybook && npm run generate-palette`);
lines.push(`   ${'='.repeat(60)} */`);
lines.push('');

// 1. Theme-independent overlays (white-alpha, black-alpha)
lines.push('/* ---------- Overlay scales (theme-independent) ---------- */');
lines.push(readScale('white-alpha.css').trim());
lines.push('');
lines.push(readScale('black-alpha.css').trim());
lines.push('');

// 2. Dark scales (default :root)
lines.push('/* ---------- Dark scales (default) ---------- */');
const darkParts = [];
for (const scale of SCALES) {
  const opaque = readScale(`${scale}-dark.css`);
  const alpha  = readScale(`${scale}-dark-alpha.css`);
  if (opaque) darkParts.push(opaque.trim());
  if (alpha)  darkParts.push(alpha.trim());
}
lines.push(transformSelectors(darkParts.join('\n\n')));
lines.push('');

// 3. Light scales
lines.push('/* ---------- Light scales ---------- */');
const lightParts = [];
for (const scale of SCALES) {
  const opaque = readScale(`${scale}.css`);
  const alpha  = readScale(`${scale}-alpha.css`);
  if (opaque) lightParts.push(opaque.trim());
  if (alpha)  lightParts.push(alpha.trim());
}
lines.push(transformSelectors(lightParts.join('\n\n')));
lines.push('');

// ---------------------------------------------------------------------------
// Write
// ---------------------------------------------------------------------------

fs.writeFileSync(OUT_FILE, lines.join('\n'));

const stat = fs.statSync(OUT_FILE);
const kb   = (stat.size / 1024).toFixed(1);

console.log(`✓ Written ${OUT_FILE} (${kb} KB)`);
console.log(`  ${SCALES.length} scales × (opaque + alpha) × 2 themes`);
console.log(`  + white-alpha + black-alpha`);
console.log(`  Source: @radix-ui/colors v${pkg.version}`);
